# Dockerfile
# Use the official Node.js image
FROM node:20.15

# Set the working directory inside the container
WORKDIR /app

# Copy the application files into the container (if needed)
COPY . .

# Install any dependencies (if you have a package.json)
# RUN npm install

# Default command (this will be overridden by Dockerode)
CMD ["node"]

